# storing API data 
smtp_account = "change-me"        //SMTP sendgrid or...
smtp_password = "change-me"      //SMTP sendgrid or...
wp_acc = "change-me"        //WordPress admin acccount
wp_password = "change-me"          //WordPress admin acccount
